<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Client;
use App\Models\Tenant;

class ClientSeeder extends Seeder
{
    public function run(): void
    {
        // Pega o id do Tenant ativo para associar os clientes corretamente à sua empresa
        $tenantId = Tenant::first()?->id ?? null;

        $clients = [
            [
                'name' => 'CONSTRUTORA ALFA LTDA',
                'fantasy_name' => 'ALFA ENGENHARIA',
                'document' => '12.345.678/0001-90',
                'state_registration' => '111.222.333.444',
                'municipal_registration' => '5556667',
                'tax_regime' => 'Lucro Presumido',
                'address' => 'Av. Paulista, 1500 - 10º Andar',
                'address_complement' => 'Conjunto 101',
                'neighborhood' => 'Bela Vista',
                'city' => 'São Paulo',
                'state' => 'SP',
                'zip_code' => '01310-200',
                'delivery_address' => 'Canteiro de Obras Residencial Sol - Av. das Américas, 450, Campinas - SP',
                'site_manager' => 'Eng. Roberto Silva',
                'site_phone' => '(19) 98765-4321',
                'phone' => '(11) 3211-0000',
                'whatsapp' => '(11) 99999-1111',
                'email_financial' => 'financeiro@construtoraalfa.com.br',
                'email_purchasing' => 'suprimentos@construtoraalfa.com.br',
                'legal_name' => 'Carlos Alberto Siqueira',
                'legal_cpf' => '123.456.789-00',
                'legal_rg' => '12.345.678-9',
                'legal_role' => 'Sócio Administrador',
                // Checklist
                'doc_cnpj' => true,
                'doc_statute' => true,
                'doc_id' => true,
                'doc_proxy' => false,
                'doc_address' => true,
                'doc_art' => true,
                'doc_registration_form' => true,
                // Risco
                'check_internal_fraud' => true,
                'check_blacklist' => true,
                'check_credit_bureau' => true,
                'credit_score' => 850,
                'check_query_history' => true,
                'check_sinintegra' => true,
                'commercial_references' => 'Fornecedor Cementos S.A.: Cliente excelente, pontualidade de 100% nos últimos 24 meses. Maquinários devolvidos em perfeito estado.',
            ],
            [
                'name' => 'MEGA EVENTOS E ESTRUTURAS S/A',
                'fantasy_name' => 'MEGA PALCO',
                'document' => '98.765.432/0001-10',
                'state_registration' => '444.333.222.111',
                'municipal_registration' => '9988775',
                'tax_regime' => 'Lucro Real',
                'address' => 'Rua das Olimpíadas, 200',
                'address_complement' => 'Galpão B',
                'neighborhood' => 'Vila Olímpia',
                'city' => 'São Paulo',
                'state' => 'SP',
                'zip_code' => '04551-000',
                'delivery_address' => 'Arena Multiuso - Rodovia Dom Pedro I, Km 120, Valinhos - SP',
                'site_manager' => 'Marcos Souza (Produtor Geral)',
                'site_phone' => '(11) 98111-2222',
                'phone' => '(11) 4004-5566',
                'whatsapp' => '(11) 98222-3333',
                'email_financial' => 'nfe@megaeventos.com.br',
                'email_purchasing' => 'compras@megaeventos.com.br',
                'legal_name' => 'Ricardo Magalhães Neto',
                'legal_cpf' => '987.654.321-11',
                'legal_rg' => '45.678.912-3',
                'legal_role' => 'Diretor de Operações',
                // Checklist
                'doc_cnpj' => true,
                'doc_statute' => true,
                'doc_id' => true,
                'doc_proxy' => true,
                'doc_address' => true,
                'doc_art' => true,
                'doc_registration_form' => true,
                // Risco
                'check_internal_fraud' => true,
                'check_blacklist' => true,
                'check_credit_bureau' => true,
                'credit_score' => 720,
                'check_query_history' => true,
                'check_sinintegra' => true,
                'commercial_references' => 'Locações Top SP: Apresentou atraso pontual de 5 dias na última fatura devido a repasse do contratante, mas regularizado sem protestos. Bem conservador com geradores.',
            ],
            [
                'name' => 'MINERACAO VALE DO SOL LTDA',
                'fantasy_name' => 'VALE DO SOL',
                'document' => '45.111.222/0002-33',
                'state_registration' => '555.888.999.000',
                'municipal_registration' => '12345',
                'tax_regime' => 'Lucro Presumido',
                'address' => 'Fazenda Boa Vista, S/N',
                'address_complement' => 'Zona Rural',
                'neighborhood' => 'Distrito Industrial',
                'city' => 'Sorocaba',
                'state' => 'SP',
                'zip_code' => '18000-000',
                'delivery_address' => 'Área de Extração 04 - Estrada Velha de Ititu, Km 12, Indaiatuba - SP',
                'site_manager' => 'Técnico Sandro Santos',
                'site_phone' => '(15) 99144-5566',
                'phone' => '(15) 3222-1122',
                'whatsapp' => '(15) 99655-4433',
                'email_financial' => 'contabilidade@mineracaovalesol.com.br',
                'email_purchasing' => 'suprimentos@mineracaovalesol.com.br',
                'legal_name' => 'Antônio Marcos de Oliveira',
                'legal_cpf' => '444.555.666-77',
                'legal_rg' => '23.411.522-4',
                'legal_role' => 'Administrador Geral',
                // Checklist
                'doc_cnpj' => true,
                'doc_statute' => true,
                'doc_id' => true,
                'doc_proxy' => false,
                'doc_address' => true,
                'doc_art' => false,
                'doc_registration_form' => true,
                // Risco
                'check_internal_fraud' => true,
                'check_blacklist' => true,
                'check_credit_bureau' => true,
                'credit_score' => 910,
                'check_query_history' => true,
                'check_sinintegra' => true,
                'commercial_references' => 'Caterpillar Brasil Fornecimentos: Cliente categoria Premium. Histórico impecável de manutenção preventiva nos motores alugados anteriormente.',
            ],
            [
                'name' => 'CONCRETO FORTE ENGENHARIA ESTRUTURAL',
                'fantasy_name' => 'CONCRETO FORTE',
                'document' => '33.444.555/0001-66',
                'state_registration' => '777.666.555.444',
                'municipal_registration' => '445522',
                'tax_regime' => 'Simples Nacional',
                'address' => 'Rua do Vergueiro, 3500',
                'address_complement' => 'Sala 42',
                'neighborhood' => 'Vila Mariana',
                'city' => 'São Paulo',
                'state' => 'SP',
                'zip_code' => '04102-000',
                'delivery_address' => 'Fundação do Condomínio Pátio Sul - Av. John Boyd Dunlop, 1200, Campinas - SP',
                'site_manager' => 'Mestre de Obras Almir',
                'site_phone' => '(19) 98855-1122',
                'phone' => '(11) 5577-8899',
                'whatsapp' => '(11) 97755-8822',
                'email_financial' => 'financeiro@concretoforte.eng.br',
                'email_purchasing' => 'compras@concretoforte.eng.br',
                'legal_name' => 'Fernando Henrique Justo',
                'legal_cpf' => '222.333.444-55',
                'legal_rg' => '11.222.333-4',
                'legal_role' => 'Sócio Técnico',
                // Checklist
                'doc_cnpj' => true,
                'doc_statute' => true,
                'doc_id' => true,
                'doc_proxy' => false,
                'doc_address' => true,
                'doc_art' => true,
                'doc_registration_form' => true,
                // Risco
                'check_internal_fraud' => true,
                'check_blacklist' => true,
                'check_credit_bureau' => true,
                'credit_score' => 610,
                'check_query_history' => true,
                'check_sinintegra' => true,
                'commercial_references' => 'Pedreira Campinas S/A: Score regular, cumpre os acordos comerciais de faturamento de insumos básicos com variação de até 10 dias do vencimento padrão.',
            ],
            [
                'name' => 'INDUSTRIAS QUIMICAS DO BRASIL LTDA',
                'fantasy_name' => 'IQB QUIMICA',
                'document' => '55.666.777/0001-88',
                'state_registration' => '999.111.222.333',
                'municipal_registration' => '889911',
                'tax_regime' => 'Lucro Real',
                'address' => 'Av. Industrial, 4000',
                'address_complement' => 'Distrito Químico',
                'neighborhood' => 'Industrial',
                'city' => 'Paulínia',
                'state' => 'SP',
                'zip_code' => '13140-000',
                'delivery_address' => 'Unidade de Resfriamento de Caldeiras (Parada de Manutenção) - Av. Industrial, 4000, Paulínia - SP',
                'site_manager' => 'Eng. Químico Fabio Lima',
                'site_phone' => '(19) 97100-2030',
                'phone' => '(19) 3874-9000',
                'whatsapp' => '(19) 97144-8000',
                'email_financial' => 'ap@iqbquimica.com.br',
                'email_purchasing' => 'procurement@iqbquimica.com.br',
                'legal_name' => 'Beatriz Helena Von Wald',
                'legal_cpf' => '555.666.777-88',
                'legal_rg' => '33.444.555-6',
                'legal_role' => 'Diretora Executiva',
                // Checklist
                'doc_cnpj' => true,
                'doc_statute' => true,
                'doc_id' => true,
                'doc_proxy' => true,
                'doc_address' => true,
                'doc_art' => true,
                'doc_registration_form' => true,
                // Risco
                'check_internal_fraud' => true,
                'check_blacklist' => true,
                'check_credit_bureau' => true,
                'credit_score' => 990,
                'check_query_history' => true,
                'check_sinintegra' => true,
                'commercial_references' => 'Gases Atmosféricos S/A: Empresa multinacional com altíssimo score e compliance rigoroso. Locações autorizadas sem ressalvas.',
            ],
        ];

        foreach ($clients as $clientData) {
            // Insere o ID do Tenant dinamicamente em cada registro para respeitar a arquitetura
            if ($tenantId) {
                $clientData['tenant_id'] = $tenantId;
            }
            Client::create($clientData);
        }
    }
}