<x-filament::icon-button
    color="gray"
    icon="heroicon-o-question-mark-circle"
    icon-size="lg"
    label="Ajuda"
    tooltip="Ajuda"
    href="https://academy.oravel.com.br/"
    target="_blank"
    rel="noopener"
    tag="a"
/>
