<?php

/**
 * Módulos de MENU: cada menu pai (Relatórios > Análises, Gestão de Estoque...) e cada tela
 * avulsa (PMP, Relatórios, Pátio...) vira uma chave de contrato, para a Central poder
 * ligar/desligar o menu inteiro. `herda` lista os módulos que já liberavam a tela antes
 * de ela ter chave própria: a migração liga a chave nos contratos que tinham algum deles
 * (ou em todos, quando a lista é vazia), para ninguém perder menu ao publicar.
 */
return [
    'menu_almoxarifado' => [
        'label' => 'Menu: Materiais e Peças → Gestão de Estoque',
        'grupo' => 'Materiais e Peças',
        'menu' => 'Gestão de Estoque',
        'slug' => 'almoxarifado',
        'herda' => ['tabela_internal_units', 'tabela_material_categories', 'tabela_material_location_stock', 'tabela_materials', 'tabela_material_stock_takes', 'tabela_parts', 'tabela_storage_locations', 'tabela_warehouses', 'ia_diagnostico_avarias', 'tabela_material_stock_movements'],
    ],
    'menu_alocacao_tecnicos_pmp' => [
        'label' => 'Tela: PMP → Alocação de Técnicos',
        'grupo' => 'PMP',
        'menu' => 'Alocação de Técnicos',
        'slug' => 'alocacao-tecnicos-pmp',
        'herda' => ['tabela_maintenance_plans'],
    ],
    'menu_apontamento_horimetro' => [
        'label' => 'Tela: Manutenção → Apontamento de Horímetro',
        'grupo' => 'Manutenção',
        'menu' => 'Apontamento de Horímetro',
        'slug' => 'apontamento-horimetro',
        'herda' => ['tabela_horimeter_readings'],
    ],
    'menu_avarias_reincidencia' => [
        'label' => 'Tela: Relatórios → Avarias & Reincidência',
        'grupo' => 'Relatórios',
        'menu' => 'Avarias & Reincidência',
        'slug' => 'avarias-reincidencia',
        'herda' => ['tabela_equipment_damages'],
    ],
    'menu_carga_tecnica' => [
        'label' => 'Tela: Relatórios → Carga de Técnicos',
        'grupo' => 'Relatórios',
        'menu' => 'Carga de Técnicos',
        'slug' => 'carga-tecnica',
        'herda' => ['tabela_maintenance_orders'],
    ],
    'menu_cobertura_pmp' => [
        'label' => 'Tela: PMP → Cobertura de PMP',
        'grupo' => 'PMP',
        'menu' => 'Cobertura de PMP',
        'slug' => 'cobertura-pmp',
        'herda' => ['tabela_maintenance_plans'],
    ],
    'menu_compliance_status' => [
        'label' => 'Tela: Configurações → Status de Conformidade',
        'grupo' => 'Configurações',
        'menu' => 'Status de Conformidade',
        'slug' => 'compliance-status',
        'herda' => [],
    ],
    'menu_consulta_cliente_pmp' => [
        'label' => 'Tela: PMP → Consulta por Cliente',
        'grupo' => 'PMP',
        'menu' => 'Consulta por Cliente',
        'slug' => 'consulta-cliente-pmp',
        'herda' => ['tabela_maintenance_plans'],
    ],
    'menu_crm_agenda' => [
        'label' => 'Tela: Comercial → Agenda Comercial',
        'grupo' => 'Comercial',
        'menu' => 'Agenda Comercial',
        'slug' => 'crm-agenda',
        'herda' => ['tabela_crm_leads'],
    ],
    'menu_crm_mapa' => [
        'label' => 'Tela: Comercial → Mapa Comercial',
        'grupo' => 'Comercial',
        'menu' => 'Mapa Comercial',
        'slug' => 'crm-mapa',
        'herda' => ['tabela_crm_leads'],
    ],
    'menu_desempenho_tecnico' => [
        'label' => 'Tela: Relatórios → Desempenho & Retrabalho',
        'grupo' => 'Relatórios',
        'menu' => 'Desempenho & Retrabalho',
        'slug' => 'desempenho-tecnico',
        'herda' => ['tabela_maintenance_orders'],
    ],
    'menu_epi_compliance_report' => [
        'label' => 'Tela: EPI → Conformidade NR-6 (EPI)',
        'grupo' => 'EPI',
        'menu' => 'Conformidade NR-6 (EPI)',
        'slug' => 'epi-compliance-report',
        'herda' => ['tabela_epi_deliveries'],
    ],
    'menu_eventos_e_falhas' => [
        'label' => 'Tela: Relatórios → Eventos e Falhas',
        'grupo' => 'Relatórios',
        'menu' => 'Eventos e Falhas',
        'slug' => 'eventos-e-falhas',
        'herda' => ['tabela_equipment_damages', 'tabela_activity_log_entries'],
    ],
    'menu_gestao_ativos' => [
        'label' => 'Menu: Ativos → Gestão de Ativos',
        'grupo' => 'Ativos',
        'menu' => 'Gestão de Ativos',
        'slug' => 'gestao-ativos',
        'herda' => ['tabela_asset_categories', 'tabela_assets', 'tabela_checklist_groups'],
    ],
    'menu_gestao_clientes' => [
        'label' => 'Tela: Comercial → Gestão de Clientes',
        'grupo' => 'Comercial',
        'menu' => 'Gestão de Clientes',
        'slug' => 'gestao-clientes',
        'herda' => ['tabela_clients'],
    ],
    'menu_gestao_comercial' => [
        'label' => 'Menu: Comercial → Gestão Comercial',
        'grupo' => 'Comercial',
        'menu' => 'Gestão Comercial',
        'slug' => 'gestao-comercial',
        'herda' => ['tabela_clients', 'tabela_contract_measurements', 'tabela_contracts', 'assinatura_eletronica', 'tabela_fleet_statuses', 'tabela_proposta_comercial', 'tabela_quotes', 'tabela_rental_hour_franchises', 'tabela_rental_overage_charges', 'tabela_solicitacao_locacao'],
    ],
    'menu_gestao_compras' => [
        'label' => 'Menu: Materiais e Peças → Gestão de Compras',
        'grupo' => 'Materiais e Peças',
        'menu' => 'Gestão de Compras',
        'slug' => 'gestao-compras',
        'herda' => ['tabela_goods_receipts', 'tabela_material_requests', 'tabela_parts_requests', 'tabela_purchase_orders', 'tabela_suppliers'],
    ],
    'menu_gestao_crm' => [
        'label' => 'Menu: Comercial → Gestão CRM',
        'grupo' => 'Comercial',
        'menu' => 'Gestão CRM',
        'slug' => 'gestao-crm',
        'herda' => ['tabela_crm_leads', 'ia_diagnostico_avarias'],
    ],
    'menu_gestao_epi' => [
        'label' => 'Menu: EPI → Gestão de EPI',
        'grupo' => 'EPI',
        'menu' => 'Gestão de EPI',
        'slug' => 'gestao-epi',
        'herda' => ['tabela_epi_deliveries', 'tabela_epi_entries'],
    ],
    'menu_gestao_insumos' => [
        'label' => 'Menu: Itens Agregados → Insumos e Consumíveis',
        'grupo' => 'Itens Agregados',
        'menu' => 'Insumos e Consumíveis',
        'slug' => 'gestao-insumos',
        'herda' => ['tabela_aggregate_item_entries', 'tabela_aggregate_item_exits', 'tabela_aggregate_item_types'],
    ],
    'menu_gestao_itens_agregados' => [
        'label' => 'Menu: Itens Agregados → Acessórios e Componentes',
        'grupo' => 'Itens Agregados',
        'menu' => 'Acessórios e Componentes',
        'slug' => 'gestao-itens-agregados',
        'herda' => ['tabela_aggregate_item_entries', 'tabela_aggregate_item_exits', 'tabela_aggregate_items', 'tabela_aggregate_item_types'],
    ],
    'menu_logistica_fretes_transporte' => [
        'label' => 'Menu: Logística → Fretes & Transporte',
        'grupo' => 'Logística',
        'menu' => 'Fretes & Transporte',
        'slug' => 'logistica-fretes-transporte',
        'herda' => ['tabela_equipment_movements', 'tabela_equipment_pickup_requests', 'tabela_freight_carriers', 'tabela_freight_records', 'ia_diagnostico_avarias'],
    ],
    'menu_logistica_frota' => [
        'label' => 'Menu: Logística → Frota',
        'grupo' => 'Logística',
        'menu' => 'Frota',
        'slug' => 'logistica-frota',
        'herda' => ['tabela_fleet_drivers', 'tabela_fleet_maintenance_plans', 'tabela_fleet_vehicles', 'tabela_traccar_devices'],
    ],
    'menu_logistica_patio' => [
        'label' => 'Menu: Logística → Pátio',
        'grupo' => 'Logística',
        'menu' => 'Pátio',
        'slug' => 'logistica-patio',
        'herda' => ['tabela_depots', 'tabela_equipment_movements'],
    ],
    'menu_maintenancao_analise_ia' => [
        'label' => 'Menu: Manutenção → Análise (IA)',
        'grupo' => 'Manutenção',
        'menu' => 'Análise (IA)',
        'slug' => 'maintenancao-analise-ia',
        'herda' => ['ia_diagnostico_avarias'],
    ],
    'menu_maintenancao_cadastros' => [
        'label' => 'Menu: Manutenção → Cadastros',
        'grupo' => 'Manutenção',
        'menu' => 'Cadastros',
        'slug' => 'maintenancao-cadastros',
        'herda' => ['tabela_abc_matrix', 'tabela_asset_downtime_events', 'tabela_checklist_templates', 'tabela_criticality_levels', 'tabela_equipment_damages', 'tabela_equipment_replacements'],
    ],
    'menu_maintenancao_operacao' => [
        'label' => 'Menu: Manutenção → Operação',
        'grupo' => 'Manutenção',
        'menu' => 'Operação',
        'slug' => 'maintenancao-operacao',
        'herda' => ['tabela_maintenance_orders', 'tabela_preventive_maintenance_executions', 'tabela_horimeter_readings'],
    ],
    'menu_maintenance_kanban' => [
        'label' => 'Tela: Manutenção → Kanban do Pátio',
        'grupo' => 'Manutenção',
        'menu' => 'Kanban do Pátio',
        'slug' => 'maintenance-kanban',
        'herda' => ['tabela_maintenance_orders'],
    ],
    'menu_mapa_equipamentos' => [
        'label' => 'Tela: Ativos → Mapa de Equipamentos',
        'grupo' => 'Ativos',
        'menu' => 'Mapa de Equipamentos',
        'slug' => 'mapa-equipamentos',
        'herda' => ['tabela_assets'],
    ],
    'menu_nr13_compliance_dashboard' => [
        'label' => 'Tela: Conformidade NR-13 → Dashboard',
        'grupo' => 'Conformidade NR-13',
        'menu' => 'Dashboard',
        'slug' => 'nr13-compliance-dashboard',
        'herda' => ['tabela_nr13_documents'],
    ],
    'menu_painel_criticidade' => [
        'label' => 'Tela: Relatórios → Painel de Criticidade',
        'grupo' => 'Relatórios',
        'menu' => 'Painel de Criticidade',
        'slug' => 'painel-criticidade',
        'herda' => ['tabela_assets'],
    ],
    'menu_painel_pmp' => [
        'label' => 'Tela: PMP → Dashboard PMP',
        'grupo' => 'PMP',
        'menu' => 'Dashboard PMP',
        'slug' => 'painel-pmp',
        'herda' => ['tabela_maintenance_plans'],
    ],
    'menu_painel_sla_emergencia' => [
        'label' => 'Tela: Relatórios → Painel de SLA',
        'grupo' => 'Relatórios',
        'menu' => 'Painel de SLA',
        'slug' => 'painel-sla-emergencia',
        'herda' => ['tabela_maintenance_orders'],
    ],
    'menu_patio_aprovacoes' => [
        'label' => 'Tela: Logística → Aprovações do Pátio',
        'grupo' => 'Logística',
        'menu' => 'Aprovações do Pátio',
        'slug' => 'patio-aprovacoes',
        'herda' => ['tabela_equipment_movements'],
    ],
    'menu_patio_chegadas' => [
        'label' => 'Tela: Logística → Chegadas no Pátio',
        'grupo' => 'Logística',
        'menu' => 'Chegadas no Pátio',
        'slug' => 'patio-chegadas',
        'herda' => ['tabela_equipment_movements'],
    ],
    'menu_planta_baixa_patio_ativos' => [
        'label' => 'Tela: Ativos → Planta Baixa (Pátio de Ativos)',
        'grupo' => 'Ativos',
        'menu' => 'Planta Baixa (Pátio de Ativos)',
        'slug' => 'planta-baixa-patio-ativos',
        'herda' => ['tabela_assets'],
    ],
    'menu_preventive_maintenance_kanban' => [
        'label' => 'Tela: PMP → Kanban Preventivas',
        'grupo' => 'PMP',
        'menu' => 'Kanban Preventivas',
        'slug' => 'preventive-maintenance-kanban',
        'herda' => ['tabela_maintenance_plans'],
    ],
    'menu_proposta_comercial_kanban' => [
        'label' => 'Tela: Comercial → Kanban Comercial',
        'grupo' => 'Comercial',
        'menu' => 'Kanban Comercial',
        'slug' => 'proposta-comercial-kanban',
        'herda' => ['tabela_proposta_comercial'],
    ],
    'menu_rastreamento_gps' => [
        'label' => 'Tela: Logística → Rastreamento GPS',
        'grupo' => 'Logística',
        'menu' => 'Rastreamento GPS',
        'slug' => 'rastreamento-gps',
        'herda' => ['tabela_traccar_devices'],
    ],
    'menu_relatorio_rastreamento' => [
        'label' => 'Tela: Logística → Relatório de Rastreamento',
        'grupo' => 'Logística',
        'menu' => 'Relatório de Rastreamento',
        'slug' => 'relatorio-rastreamento',
        'herda' => ['tabela_traccar_devices'],
    ],
    'menu_relatorios' => [
        'label' => 'Tela: Relatórios → Relatórios',
        'grupo' => 'Relatórios',
        'menu' => 'Relatórios',
        'slug' => 'relatorios',
        'herda' => ['tabela_maintenance_orders'],
    ],
    'menu_relatorios_analises' => [
        'label' => 'Menu: Relatórios → Análises',
        'grupo' => 'Relatórios',
        'menu' => 'Análises',
        'slug' => 'relatorios-analises',
        'herda' => ['ia_diagnostico_avarias', 'tabela_equipment_damages', 'tabela_maintenance_orders'],
    ],
    'menu_relatorios_historicos_logs' => [
        'label' => 'Menu: Relatórios → Históricos & Logs',
        'grupo' => 'Relatórios',
        'menu' => 'Históricos & Logs',
        'slug' => 'relatorios-historicos-logs',
        'herda' => ['tabela_abc_matrix_histories', 'tabela_activity_log_entries', 'tabela_horimeter_readings', 'tabela_maintenance_status_histories', 'tabela_notification_logs', 'tabela_equipment_damages'],
    ],
    'menu_relatorios_paineis' => [
        'label' => 'Menu: Relatórios → Painéis',
        'grupo' => 'Relatórios',
        'menu' => 'Painéis',
        'slug' => 'relatorios-paineis',
        'herda' => ['tabela_assets', 'tabela_maintenance_orders'],
    ],
    'menu_requisicao_reposicao_estoque' => [
        'label' => 'Tela: Materiais e Peças → Reposição de Estoque',
        'grupo' => 'Materiais e Peças',
        'menu' => 'Reposição de Estoque',
        'slug' => 'requisicao-reposicao-estoque',
        'herda' => ['tabela_material_requests'],
    ],
    'menu_reservas_urgentes' => [
        'label' => 'Tela: Manutenção → Reservas Urgentes',
        'grupo' => 'Manutenção',
        'menu' => 'Reservas Urgentes',
        'slug' => 'reservas-urgentes',
        'herda' => ['tabela_maintenance_orders'],
    ],
    'menu_transferencia_estoque' => [
        'label' => 'Tela: Materiais e Peças → Transferência para Volante',
        'grupo' => 'Materiais e Peças',
        'menu' => 'Transferência para Volante',
        'slug' => 'transferencia-estoque',
        'herda' => ['tabela_parts'],
    ],
    'menu_responsaveis_avisos' => [
        'label' => 'Tela: Configurações → Responsáveis pelos Avisos',
        'grupo' => 'Configurações',
        'menu' => 'Responsáveis pelos Avisos',
        'slug' => 'responsaveis-avisos',
        'herda' => [],
    ],
    'menu_email_da_empresa' => [
        'label' => 'Tela: Configurações → E-mail da Empresa',
        'grupo' => 'Configurações',
        'menu' => 'E-mail da Empresa',
        'slug' => 'email-da-empresa',
        'herda' => [],
    ],
    'menu_whatsapp_da_empresa' => [
        'label' => 'Tela: Configurações → WhatsApp da Empresa',
        'grupo' => 'Configurações',
        'menu' => 'WhatsApp da Empresa',
        'slug' => 'whatsapp-da-empresa',
        'herda' => [],
    ],
    'menu_whatsapp' => [
        'label' => 'Tela: Comercial → WhatsApp',
        'grupo' => 'Comercial',
        'menu' => 'WhatsApp',
        'slug' => 'whatsapp',
        'herda' => [],
    ],
];
